import json
import shutil
from pathlib import Path

REQUIRED_FIELDS = [
    "name", "subscriber_initials", "dob", "pob", "tob",
    "coverage_start", "coverage_end", "kit"
]

MAX_MMFSN_PER_GAME = 5


def clean_subscriber_file(raw_file_path: Path, root: Path):
    """
    Cleans ONE legacy subscriber file and converts it into V3 intake format.
    - Archives original file
    - Creates clean V3 subscriber file
    - Creates MMFSN profile file
    """

    print(f"\n[CLEANER] Processing file: {raw_file_path.name}")

    # Load raw JSON data
    with raw_file_path.open("r", encoding="utf-8") as f:
        raw_data = json.load(f)

    # Validate fields
    missing = [f for f in REQUIRED_FIELDS if f not in raw_data]
    if missing:
        print(f"[CLEANER ERROR] Missing required fields: {missing}")
        return False

    initials = raw_data["subscriber_initials"].upper()

    # ---------------------------------------------------------
    # 1. Create ARCHIVE copy of original file
    # ---------------------------------------------------------

    archive_dir = root / "archive" / "subscribers_raw"
    archive_dir.mkdir(parents=True, exist_ok=True)

    archive_path = archive_dir / f"{initials}_raw.json"
    shutil.copy(raw_file_path, archive_path)
    print(f"[CLEANER] Archived original file → {archive_path}")

    # ---------------------------------------------------------
    # 2. Extract MMFSN into its own profile file
    # ---------------------------------------------------------

    mmfsn_data = raw_data.get("mmfsn", {})
    mmfsn_clean = {
        "Cash3": [],
        "Cash4": []
    }

    # Apply cap logic
    if "Cash3" in mmfsn_data:
        mmfsn_clean["Cash3"] = mmfsn_data["Cash3"][-MAX_MMFSN_PER_GAME:]

    if "Cash4" in mmfsn_data:
        mmfsn_clean["Cash4"] = mmfsn_data["Cash4"][-MAX_MMFSN_PER_GAME:]

    mmfsn_dir = root / "data" / "mmfsn_profiles"
    mmfsn_dir.mkdir(parents=True, exist_ok=True)

    mmfsn_path = mmfsn_dir / f"{initials}_mmfsn.json"
    mmfsn_payload = {
        "initials": initials,
        "mmfsn_numbers": mmfsn_clean,
        "weight": 0.60,
        "notes": "Generated by V3 Cleaner"
    }

    with mmfsn_path.open("w", encoding="utf-8") as f:
        json.dump(mmfsn_payload, f, indent=2)

    print(f"[CLEANER] MMFSN extracted → {mmfsn_path}")

    # ---------------------------------------------------------
    # 3. Build clean V3 intake file
    # ---------------------------------------------------------

    clean_payload = {
        "name": raw_data["name"],
        "initials": initials,
        "kit": raw_data["kit"],
        "coverage_start": raw_data["coverage_start"],
        "coverage_end": raw_data["coverage_end"],
        "birthdate": raw_data["dob"],
        "birthtime": raw_data["tob"],
        "birthplace": raw_data["pob"],
        "timezone": "America/New_York"  # default for your system
    }

    out_dir = root / "data" / "subscribers"
    out_dir.mkdir(parents=True, exist_ok=True)

    clean_file_path = out_dir / f"{initials}.json"
    with clean_file_path.open("w", encoding="utf-8") as f:
        json.dump(clean_payload, f, indent=2)

    print(f"[CLEANER] Clean V3 file created → {clean_file_path}")

    # ---------------------------------------------------------
    # 4. Remove original file from the subscribers folder
    # ---------------------------------------------------------

    raw_file_path.unlink()
    print(f"[CLEANER] Removed original legacy file from subscribers folder.")

    return True
