#!/usr/bin/env python3
"""
Check Test Subscriber Outputs
==============================
Analyzes what outputs are being generated by the test subscribers
"""

import os
import json
from pathlib import Path
from datetime import datetime, timedelta

def check_test_outputs():
    """Check what outputs are being generated by test subscribers."""
    
    project_root = Path(__file__).parent.absolute()
    outputs_dir = project_root / "outputs"
    
    print("🔍 CHECKING TEST SUBSCRIBER OUTPUTS")
    print("=" * 50)
    
    # Look for any directories that might contain test subscriber results
    test_patterns = ["TEST", "BOOK3_TEST", "test", "0001", "0002", "0003"]
    
    found_outputs = []
    
    for output_dir in outputs_dir.iterdir():
        if output_dir.is_dir():
            dir_name = output_dir.name.upper()
            
            # Check if directory name contains test indicators
            if any(pattern.upper() in dir_name for pattern in test_patterns):
                found_outputs.append(output_dir)
                print(f"📁 Found potential test output: {output_dir.name}")
                
                # Check contents
                json_files = list(output_dir.glob("*.json"))
                if json_files:
                    print(f"   📄 Contains {len(json_files)} JSON files")
                    
                    # Check today's file
                    today_file = output_dir / "2025-12-23.json"
                    if today_file.exists():
                        print(f"   ✅ Has today's predictions (2025-12-23.json)")
                        
                        try:
                            with open(today_file, 'r') as f:
                                data = json.load(f)
                            
                            if "predictions" in data:
                                print(f"   🎯 Contains predictions:")
                                for game, pred in data["predictions"].items():
                                    conf = pred.get("confidence", 0)
                                    print(f"      • {game}: {pred.get('prediction', 'N/A')} (conf: {conf:.1%})")
                            else:
                                print(f"   ⚠️ No predictions section found")
                                
                        except Exception as e:
                            print(f"   ❌ Error reading file: {e}")
                    else:
                        print(f"   ⚠️ No today's file (2025-12-23.json)")
                else:
                    print(f"   📭 No JSON files found")
    
    if not found_outputs:
        print("⚠️ No test outputs found using pattern matching")
        print("\n🔍 Let me check all recent directories...")
        
        # Check all directories modified in the last hour
        recent_dirs = []
        cutoff_time = datetime.now() - timedelta(hours=1)
        
        for output_dir in outputs_dir.iterdir():
            if output_dir.is_dir():
                try:
                    mod_time = datetime.fromtimestamp(output_dir.stat().st_mtime)
                    if mod_time > cutoff_time:
                        recent_dirs.append((output_dir, mod_time))
                except:
                    continue
        
        if recent_dirs:
            print(f"📁 Found {len(recent_dirs)} recent directories:")
            recent_dirs.sort(key=lambda x: x[1], reverse=True)
            
            for output_dir, mod_time in recent_dirs[:10]:  # Show top 10
                print(f"   • {output_dir.name} (modified: {mod_time.strftime('%H:%M:%S')})")
                
                # Quick check if it has JSON files
                json_files = list(output_dir.glob("*.json"))
                if json_files:
                    print(f"     📄 {len(json_files)} JSON files")
        else:
            print("📭 No recent directories found")
    
    return found_outputs

def main():
    check_test_outputs()

if __name__ == "__main__":
    main()