#!/usr/bin/env python3
"""
Quick Confidence Checker
========================
Check actual confidence levels being generated by our processed TEST subscribers
"""

import os
import json
import sys
from pathlib import Path

# Project root setup
PROJECT_ROOT = Path(__file__).parent.absolute()

def check_test_subscriber_confidences():
    """Check confidence levels from existing TEST subscriber outputs."""
    
    outputs_dir = PROJECT_ROOT / "outputs"
    
    print("🔍 QUICK CONFIDENCE ANALYSIS")
    print("=" * 60)
    print(f"📁 Checking: {outputs_dir}")
    print()
    
    # Find TEST subscriber directories
    test_dirs = []
    for d in outputs_dir.iterdir():
        if d.is_dir() and "TEST" in d.name:
            test_dirs.append(d)
    
    print(f"📊 Found {len(test_dirs)} TEST subscriber directories")
    
    if not test_dirs:
        print("❌ No TEST subscriber directories found!")
        return
    
    # Analyze first 5 for quick sample
    sample_dirs = test_dirs[:5]
    
    for test_dir in sample_dirs:
        print(f"\n📂 {test_dir.name}")
        print("-" * 50)
        
        # Get a random JSON file to check structure
        json_files = list(test_dir.glob("*.json"))
        if not json_files:
            print("   ❌ No JSON files found")
            continue
        
        # Check the first JSON file
        sample_file = json_files[0]
        try:
            with open(sample_file, 'r') as f:
                data = json.load(f)
            
            print(f"   📄 Sample file: {sample_file.name}")
            
            # Check for predictions structure
            if "picks" in data:
                picks = data["picks"]
                print(f"   🎮 Games found: {list(picks.keys())}")
                
                for game, game_data in picks.items():
                    print(f"      🎯 {game}: {len(game_data.get('lane_system', []) + game_data.get('lane_mmfsn', []))} picks")
                    
            # Check for score/confidence data
            if "score" in data:
                print(f"   📊 Base score: {data['score']}")
                
            if "score_components" in data:
                components = data["score_components"]
                print(f"   🔧 Score components: {len(components)} items")
                
            # Look for any confidence fields
            confidence_fields = []
            def find_confidence_fields(obj, prefix=""):
                if isinstance(obj, dict):
                    for key, value in obj.items():
                        full_key = f"{prefix}.{key}" if prefix else key
                        if "confidence" in key.lower():
                            confidence_fields.append((full_key, value))
                        elif isinstance(value, (dict, list)):
                            find_confidence_fields(value, full_key)
                elif isinstance(obj, list):
                    for i, item in enumerate(obj):
                        if isinstance(item, (dict, list)):
                            find_confidence_fields(item, f"{prefix}[{i}]")
            
            find_confidence_fields(data)
            
            if confidence_fields:
                print("   💎 Confidence fields found:")
                for field, value in confidence_fields:
                    print(f"      {field}: {value}")
            else:
                print("   ⚠️  No explicit confidence fields found")
                
        except Exception as e:
            print(f"   ❌ Error reading {sample_file.name}: {e}")
    
    # Check what date range these files cover
    print(f"\n📅 DATE RANGE ANALYSIS")
    print("-" * 50)
    
    first_dir = test_dirs[0]
    json_files = sorted(list(first_dir.glob("*.json")))
    if json_files:
        start_date = json_files[0].stem
        end_date = json_files[-1].stem
        print(f"   📅 Date range: {start_date} to {end_date}")
        print(f"   📊 Total days: {len(json_files)} days")
        
        # Check if today's date is included
        if "2025-12-22.json" in [f.name for f in json_files]:
            print("   ✅ Today's date (2025-12-22) IS included")
        else:
            print("   ❌ Today's date (2025-12-22) is NOT included")

if __name__ == "__main__":
    check_test_subscriber_confidences()