# ============================================
# BOOK3 MASS RUNNER – NO BRACES VERSION
# ============================================

Write-Host "--------------------------------------------"
Write-Host "  BOOK3 MASS RUNNER – Starting"
Write-Host "--------------------------------------------"

$root = "C:\MyBestOdds\jackpot_system_v3"
$subscriberPath = "$root\data\subscribers\BOOK3"
$logFile = "$root\BOOK3_run_log.txt"

# Reset log file
"BOOK3 MASS RUN – $(Get-Date)" | Out-File $logFile -Encoding utf8
"---------------------------------------------" | Out-File $logFile -Append

# List files (one per line)
$files = Get-ChildItem "$subscriberPath\*.json" | Select-Object -ExpandProperty Name

Write-Host "Found $($files.Count) subscriber files."
"Found $($files.Count) subscriber files." | Out-File $logFile -Append

# ===== RUN ONE FILE PER COMMAND (no braces) =====
foreach ($f in $files)
`echo FILE:$f`

# The backtick above breaks the loop OUTSIDE of a block.
# Now manually run the command lines generated by the loop

$cmdList = Get-ChildItem "$subscriberPath\*.json" | ForEach-Object {
    "python run_kit_v3.py `"$($_.Name)`" BOOK3"
}

# Execute each command
foreach ($cmd in $cmdList)
`echo CMD:$cmd`

# Now execute
foreach ($cmd in $cmdList)
    Invoke-Expression $cmd

Write-Host ""
Write-Host "--------------------------------------------"
Write-Host "  BOOK3 MASS RUN – COMPLETE"
Write-Host "  Log saved to: $logFile"
Write-Host "--------------------------------------------"
